default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: twitter_exam_development
test:
  <<: *default
  database: twitter_exam_test
production:
  <<: *default
  database: twitter_exam_production
  username: twitter_exam
  password: <%= ENV['TWITTER_EXAM_DATABASE_PASSWORD'] %>
